DROP TABLE IF EXISTS
    CreneauConnexionUtilisateur,
    CreneauConnexionBillet,
    EtablissementPolitique,
    CategorieBillet,
    CategorieEvenement,
    EvenementEtablissement,
    Echange,
    Achat,
    Reservation,
    CreneauConnexion,
    Billet,
    PolitiqueEtablissement,
    Etablissement,
    Categorie,
    Evenement,
    Utilisateur,
    TEMPS
CASCADE;